---
- hosts: hosts
  become: true
  tasks:
    - name: upgrade Debian
      apt:
        update_cache: yes
        upgrade: yes
      when: ansible_facts["os_family"] == "Debian"

    - name: upgrade RedHat
      dnf:
        name: "*"
        state: latest
        update_cache: yes
      when: ansible_facts["os_family"] == "RedHat"

- hosts: ubuntu-vm
  become: true
  tasks:
  
    - name: add GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
  
    - name: add docker repository to apt
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present    
  
    - name: install docker
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
  
    - name: check docker is active
      service:
        name: docker
        state: started
        enabled: yes
  
    - name: Ensure group "docker" exists
      ansible.builtin.group:
        name: docker
        state: present

    - name: download minikube
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
        dest: /minikube_latest_amd64.deb

    - name: install minikube
      apt:
        deb: /minikube_latest_amd64.deb
        state: present