$ANSIBLE_VAULT;1.1;AES256
62343064373737643031636534663031363330323634363434333063653563653864373930663831
6637316534616436333366653739326437643237316237300a313339333231313631356466346131
31306231636237363364326465663032363039633562396662383637363539366339323130656230
6164323230373638650a656639656333386162303932646239313231333137333334343133613038
39613766643863613461636339663035346237323235376561303164613333636363
